name: fgp
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - anyio==4.9.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.7.1
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - ghp-import==2.1.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - graphviz==0.20.3
      - griffe==1.5.7
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupytext==1.16.7
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mistune==3.1.3
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-jupyter==0.25.1
      - mkdocs-material==9.6.5
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.28.2
      - mkdocstrings-python==1.16.2
      - mknotebooks==0.8.0
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbval==0.11.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - numpy==2.2.3
      - overrides==7.7.0
      - packaging==24.2
      - paginate==0.5.7
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.19.1
      - pymdown-extensions==10.14.3
      - pyparsing==3.2.1
      - pytest==8.3.4
      - pytest-doctest-mkdocstrings==0.1.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - pyzmq==26.3.0
      - qmcpy==1.6.2.1
      - qmctoolscl==1.1.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - scipy==1.15.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.6.0
      - torchviz==0.0.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - tueplots==0.2.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
