name: fgp
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - babel==2.17.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - ghp-import==2.1.0
      - griffe==1.5.7
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.6.5
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.28.2
      - mkdocstrings-python==1.16.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.3
      - packaging==24.2
      - paginate==0.5.7
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pygments==2.19.1
      - pymdown-extensions==10.14.3
      - pyparsing==3.2.1
      - pytest==8.3.4
      - pytest-doctest-mkdocstrings==0.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - qmcpy==1.6.2
      - qmctoolscl==1.1.2
      - regex==2024.11.6
      - requests==2.32.3
      - scipy==1.15.2
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.6.0
      - tueplots==0.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
